Repository Nefariusek/CodersCamp2021.Project.Typescript.Coderscassonne, pull requests merged in 2022-05, with the labels that each got.

#91 fix a bug related to determining the active player
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
Labels: bug

#94 Enhancement/issue 83
  frontend/src/components/Button/Button.tsx
  frontend/src/components/CreatePlayer/AddedPlayers.tsx
  frontend/src/components/CreatePlayer/CreatePlayer.tsx
  frontend/src/components/GameTimer/GameTimer.tsx
  frontend/src/views/CreditsPage.tsx
  frontend/src/views/CustomModePage.tsx
  frontend/src/views/HomePage.tsx
  frontend/src/views/HowToPlayPage.tsx
  frontend/src/views/SettingsPage.tsx
Labels: enhancement

#95 Feature/issue 86
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/views/CustomModePage.tsx
  frontend/tailwind.config.js
Labels: enhancement, Sprint_1

#105 Enhancement/issue 85
  frontend/src/components/CreatePlayer/AddedPlayers.tsx
  frontend/src/components/CreatePlayer/CreatePlayer.tsx
  frontend/src/components/Tooltip/Tooltip.tsx
Labels: enhancement

#106 Enhancement/issue 87
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/Button.tsx
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/GameTimer/GameTimer.tsx
  frontend/src/components/Legend/Legend.tsx
  frontend/src/constants/gameDefaults.ts
  frontend/src/views/Game.tsx
  frontend/src/views/HomePage.tsx
Labels: enhancement

#113 Hotfix/tailwind update
  frontend/tailwind.config.js
Labels: enhancement

#111 remove bug, add select feature
  frontend/src/views/CustomModePage.tsx
Labels: bug

#108 feature/issue-88
  frontend/src/components/GameTimer/GameTimer.tsx
  frontend/src/components/NextPhaseButton/NextPhaseButton.tsx
  frontend/src/stores/GameStore.ts
  frontend/src/views/Game.tsx
Labels: enhancement, frontend

#120 Feature/issue 114
  frontend/src/components/CreatePlayer/AddedPlayers.tsx
  frontend/src/components/CreatePlayer/CreatePlayer.tsx
  frontend/src/components/GameBoard/GameBoard.functions.ts
  frontend/src/model/Project.ts
  frontend/src/stores/PlayersStore.ts
  frontend/src/stores/ProjectStore.ts
  frontend/src/stores/RootStore.ts
  frontend/src/views/CreatePlayersPage.tsx
  frontend/src/views/Game.tsx
  frontend/src/views/HomePage.tsx
Labels: help wanted

#123 Hotfix/issue 103
  backend/src/constants/locations.ts
  backend/src/constants/tilesData.ts
  frontend/src/__test__/components/GameModeParser.test.tsx
  frontend/src/components/Legend/Legend.tsx
  frontend/src/mocks/mocksTiles.ts
  frontend/src/stores/GameStore.ts
Labels: backend

#126 Enhancement/logo
  frontend/src/components/Layout.tsx
Labels: enhancement

#128 Enhancement/modals refactoring
  backend/.eslintrc.js
  frontend/src/components/Layout.tsx
  frontend/src/components/Modal/EndGameModal.tsx
  frontend/src/components/Modal/EndTurnModal.tsx
  frontend/src/components/Modal/InvalidMoveModal.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/SettingsModal.tsx
  frontend/src/components/Modal/ShowScoreModal.tsx
  frontend/src/components/Modal/WorkInProgressModal.tsx
  frontend/src/views/CreatePlayersPage.tsx
  frontend/src/views/CreditsPage.tsx
  frontend/src/views/CustomModePage.tsx
  frontend/src/views/HomePage.tsx
  frontend/src/views/HowToPlayPage.tsx
  frontend/src/views/SettingsPage.tsx
Labels: enhancement, frontend

#129 [Enhancement/Bug] Some layout fixes and improvements
  frontend/src/App.tsx
  frontend/src/components/CreatePlayer/AddedPlayers.tsx
  frontend/src/components/GameTimer/GameTimer.tsx
  frontend/src/components/Legend/Legend.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
  frontend/src/constants/paths.ts
  frontend/src/views/CustomModePage.tsx
  frontend/src/views/GameModePage.tsx
Labels: frontend

#122 Feature/issue 102
  frontend/src/model/websocket/MeeplePlacementMessage.ts
  frontend/src/model/websocket/TilePlacementMessage.ts
  frontend/src/model/websocket/WebSocketMessageParser.ts
Labels: feature, backend

#131 Hotfix/remove old landingpage
  frontend/src/App.tsx
  frontend/src/constants/paths.ts
  frontend/src/views/LandingPage.tsx
Labels: bug

#133 Feature/issue 99 and Feature/issue 132
  backend/src/app.module.ts
  backend/src/constants/webSocketEvents.ts
  backend/src/game.gateway.spec.ts
  backend/src/game.gateway.ts
  backend/src/tiles/tiles.controller.spec.ts
  backend/src/tiles/tiles.controller.ts
  backend/src/tiles/tiles.gateway.spec.ts
  backend/src/tiles/tiles.gateway.ts
  backend/src/tiles/tiles.module.ts
  backend/src/tiles/tiles.service.spec.ts
  backend/src/tiles/tiles.service.ts
  frontend/src/App.tsx
  frontend/src/components/GameBoard/GameBoard.hooks.ts
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/PlayersHand/ArrowButton.tsx
  frontend/src/components/TileContainer/TileContainer.tsx
  frontend/src/constants/webSocketEvents.ts
  frontend/src/model/Tile.ts
  frontend/src/model/websocket/WebSocketMessageParser.ts
  frontend/src/stores/GameStore.ts
Labels: feature, backend

#140 remove cardinal, add score to players info
  frontend/src/__test__/model/Project.test.ts
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
  frontend/src/model/Project.ts
  frontend/src/services/pointsPhase.functions.ts
Labels: P1

#144 add placing of meeples to gameboard
  frontend/src/__test__/model/Player.test.ts
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/TileContainer/TileContainer.tsx
  frontend/src/model/Player.ts
  frontend/src/model/Project.ts
  frontend/src/services/meeplePlacementPhase.functions.ts
  frontend/src/stores/GameStore.ts
  frontend/src/stores/RootStore.ts
Labels: P1

#143 add border in game view
  frontend/src/views/Game.tsx
Labels: frontend

#151 dropdown is hidden
  frontend/src/components/NextPhaseButton/NextPhaseButton.tsx
Labels: bug

#148 Feature/multiplayer game
  backend/src/app.messagehandler.service.ts
  backend/src/constants/webSocketEvents.ts
  backend/src/game.gateway.ts
  frontend/src/App.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/GameBoard/GameBoard.hooks.ts
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/GameModeParser.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/PasswordModal.tsx
  frontend/src/components/PlayersHand/ArrowButton.tsx
  frontend/src/components/Rooms/AvailableRooms.tsx
  frontend/src/components/Rooms/CreateRoom.tsx
  frontend/src/constants/webSocketEvents.ts
  frontend/src/model/websocket/WebSocketConnection.ts
  frontend/src/stores/GameStore.ts
  frontend/src/stores/RootStore.ts
  frontend/src/views/HomePage.tsx
  frontend/src/views/JoinRoomPage.tsx
Labels: feature, backend

#155 Feature/issue 152
  frontend/src/components/Modal/Modal.tsx
  frontend/src/mocks/mocksTiles.ts
  frontend/src/stores/GameStore.ts
  frontend/src/stores/PlayersStore.ts
  frontend/src/views/Game.tsx
  frontend/src/views/HomePage.tsx
Labels: feature, frontend

#147 Feature/nestjs api
  backend/package-lock.json
  backend/src/game.gateway.ts
  backend/src/main.ts
  backend/src/service/shuffleArray.ts
  backend/src/tiles/tiles.controller.ts
  backend/src/tiles/tiles.service.ts
  frontend/src/api/getTiles.ts
  frontend/src/components/GameBoard/GameBoard.hooks.ts
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/constants/gameDefaults.ts
  frontend/src/constants/restResources.ts
  frontend/src/model/websocket/WebSocketConnection.ts
  frontend/src/service/startGameWithTilesRetrieval.ts
  frontend/src/stores/GameStore.ts
  frontend/src/stores/RootStore.ts
  frontend/src/views/Game.tsx
  frontend/src/views/GameModePage.tsx
  frontend/src/views/HomePage.tsx
Labels: feature, backend

#160 Hotfix/game logic
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/SettingsModal.tsx
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
  frontend/src/components/ProjectList/ProjectList.tsx
  frontend/src/mocks/mocksTiles.ts
  frontend/src/model/Player.ts
  frontend/src/model/Project.ts
  frontend/src/services/meeplePlacementPhase.functions.ts
  frontend/src/services/pointsPhase.functions.ts
  frontend/src/services/tilePlacementPhase.functions.ts
  frontend/src/stores/GameStore.ts
  frontend/src/stores/PlayersStore.ts
  frontend/src/views/GameModePage.tsx
Labels: bug

#168 Feature/nestjs api database
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/tiles-db/tiles-db.controller.spec.ts
  backend/src/tiles-db/tiles-db.controller.ts
  backend/src/tiles-db/tiles-db.module.ts
  backend/src/tiles-db/tiles-db.service.spec.ts
  backend/src/tiles-db/tiles-db.service.ts
  backend/src/tiles/tiles.service.ts
Labels: feature, backend
