Repository Nefariusek/CodersCamp2021.Project.Typescript.Coderscassonne, pull requests merged in 2022-04, with the labels that each got.

#19 Feature/issue 4
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/src/__test__/model/Tile.test.ts
  frontend/src/model/Player.ts
  frontend/src/model/Tile.ts
Labels: P1

#25 Feature/issue 10 - TileContainer
  .vscode/settings.json
  frontend/.eslintrc.js
  frontend/public/Elements/Tiles/Splitters/Splitter_1.png
  frontend/public/Elements/Tiles/Splitters/Splitter_2.png
  frontend/src/App.tsx
  frontend/src/__test__/components/GameModeParser.test.tsx
  frontend/src/__test__/model/Tile.test.ts
  frontend/src/components/GameModeParser.ts
  frontend/src/components/TileContainer.tsx
  frontend/src/constants/layoutElements.ts
  frontend/src/constants/locations.ts
  frontend/src/constants/tileState.ts
  frontend/src/constants/tiles.ts
  frontend/src/mocks/mocks.ts
  frontend/src/model/Tile.ts
Labels: Sprint_1

#27 Feature/issue 17
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/constants/paths.ts
  frontend/src/views/Game.tsx
  frontend/src/views/HomePage.tsx
  frontend/src/views/LandingPage.tsx
Labels: Sprint_1, feature

#20 Feature/issue 6
  frontend/.eslintrc.js
  frontend/public/UI.md
  frontend/src/__test__/model/Meeple.test.ts
  frontend/src/__test__/model/Player.test.ts
  frontend/src/constants/gameDefaults.ts
  frontend/src/constants/technologies.ts
  frontend/src/model/Meeple.ts
  frontend/src/model/Player.ts
  frontend/src/model/Tile.ts
Labels: Sprint_1, P1, feature

#36 Feature/issue 16
  frontend/src/components/DataStoreContext/DataStoreContext.tsx
  frontend/src/index.tsx
Labels: Sprint_2, P1, feature

#37 Feature/issue 28
  frontend/public/Elements/Layout/Castle.png
  frontend/src/App.tsx
  frontend/src/components/Layout.tsx
  frontend/src/constants/labels.ts
  frontend/src/index.tsx
  frontend/src/views/HomePage.tsx
Labels: Sprint_2, Sprint_3, P1, feature

#34 Feature/issue 11 Gameboard
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__test__/App.test.tsx
  frontend/src/__test__/components/GameModeParser.test.tsx
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/PlayersHand/PlayersHand.tsx
  frontend/src/components/TileContainer/TileContainer.tsx
  frontend/src/mocks/mocks.ts
  frontend/src/views/LandingPage.tsx
Labels: Sprint_2, P1

#55 Feature/issue 32
  frontend/src/App.tsx
  frontend/src/views/CreditsPage.tsx
  frontend/src/views/HomePage.tsx
Labels: Sprint_3, feature

#57 Feature/issue 42
  frontend/src/components/DataStoreContext/DataStoreContext.tsx
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/PlayersHand/ArrowButton.tsx
  frontend/src/components/PlayersHand/PlayersHand.tsx
  frontend/src/components/TileContainer/TileContainer.tsx
  frontend/src/views/CreatePlayersPage.tsx
  frontend/src/views/Game.tsx
  frontend/src/views/LandingPage.tsx
Labels: P1

#58 add key in map in PlayersInfo
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
Labels: enhancement, Sprint_4

#60 add activateAdjacentTiles function to GameBoard
  frontend/src/components/GameBoard/GameBoard.tsx
Labels: P1

#59 add homepage link to the application title and prevent the title text…
  frontend/src/components/Layout.tsx
Labels: enhancement, Sprint_4

#63 little improvement of presentation of timer seconds
  frontend/src/components/GameTimer/GameTimer.tsx
Labels: Sprint_4

#62 fix constants with image paths
  frontend/src/constants/layoutElements.ts
Labels: Sprint_4

#61 hotfix/issue-32
  frontend/src/views/CreditsPage.tsx
Labels: Sprint_4

#64 Hotfix/image paths (non constants)
  frontend/src/components/Legend/Legend.tsx
  frontend/src/components/PlayersHand/ArrowButton.tsx
  frontend/src/constants/tiles.ts
  frontend/src/views/CustomModePage.tsx
  frontend/src/views/SettingsPage.tsx
Labels: bug, Sprint_4

#66 Feature/issue 49
  frontend/src/App.tsx
  frontend/src/__test__/components/GameModeParser.test.tsx
  frontend/src/components/DataStoreContext/DataStoreContext.tsx
  frontend/src/components/GameBoard/GameBoard.tsx
  frontend/src/components/GameTimer/GameTimer.tsx
  frontend/src/components/PlayersInfo/PlayersInfo.tsx
  frontend/src/constants/paths.ts
  frontend/src/index.tsx
  frontend/src/mocks/mocks.ts
  frontend/src/views/CreatePlayersPage.tsx
  frontend/src/views/SettingsPage.tsx
Labels: P1

#67 homepage as root
  frontend/src/App.tsx
  frontend/src/constants/paths.ts
Labels: Sprint_4

#70 Bug/issue 69
  frontend/public/Elements/Layout/Menu_tile.png
  frontend/src/App.tsx
  frontend/src/constants/layoutElements.ts
  frontend/src/views/Game.tsx
Labels: bug

#73 Feature/issue 40 - How to play page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/constants/paths.ts
  frontend/src/views/HomePage.tsx
  frontend/src/views/HowToPlayPage.tsx
Labels: Sprint_4, feature

#77 add modal to scoreboard
  frontend/src/views/HomePage.tsx
Labels: bug
